language: php

dist: focal

addons:
    apt:
        packages:
            - "libonig5"

matrix:
    include:
        - php: 7.4
          env:
            - COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.4
        - php: 8.0
        - php: 8.1
          before_install:
              - composer require --dev symfony/clock
        - php: 8.2
          before_install:
              - composer require --dev symfony/clock
        - php: 8.3
          before_install:
              - composer require --dev symfony/clock

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

install:
    - phpenv config-rm xdebug.ini
    - composer validate
    - composer update $COMPOSER_FLAGS

script:
    - vendor/bin/phpcs
    - vendor/bin/phpstan analyze -c phpstan.neon
    - vendor/bin/phpspec run -f pretty
    - vendor/bin/phpunit
