language: php

matrix:
    include:
        - php: 7.4
          env:
            - COMPOSER_FLAGS='--prefer-lowest'
        - php: 8.0

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

before_script:
    - phpenv config-rm xdebug.ini
    - composer validate
    - composer update $COMPOSER_FLAGS

script:
    - vendor/bin/phpcs
    - vendor/bin/phpstan analyze -c phpstan.neon
    - vendor/bin/phpspec run -f pretty
    - vendor/bin/phpunit
